const CONFIG = Object.freeze({
  SPREADSHEET_ID: '1brxCfiCcLS6vCcC9jEftiyTTE6CxSoYAayEEqGgNaKE',
  TIMEZONE: 'America/Sao_Paulo',
  SHEETS: Object.freeze({ PARTICIPANTES: 'PARTICIPANTES', INSCRICOES: 'INSCRICOES', PRESENCAS: 'PRESENCAS', IMPORTACOES: 'IMPORTACOES', CONFIG: 'CONFIG', INSCRICOES_LOCAL_CONTROLE: 'INSCRICOES_LOCAL_CONTROLE' }),
  HEADERS: Object.freeze({
    PARTICIPANTES: ['ID_PESSOA','NOME','NOME_NORMALIZADO','NOME_CRACHA','EMAIL','CPF','TELEFONE','NUMEROS_INSCRICAO','QTD_INSCRICOES','PRIMEIRA_INSCRICAO_EM','ULTIMA_ATUALIZACAO'],
    INSCRICOES: ['NUMERO_INSCRICAO','ID_PESSOA','ID_ORIGEM','NOME_ORIGEM','NOME_CRACHA_ORIGEM','EMAIL_ORIGEM','CPF_ORIGEM','CATEGORIA','DATA_INSCRICAO','HORA_INSCRICAO','ARQUIVO_ORIGEM','IMPORTADO_EM','ORIGEM_INSCRICAO'],
    PRESENCAS: ['ID_PRESENCA','ID_PESSOA','NUMERO_INSCRICAO_LIDO','NOME','DATA_HORA','DATA','HORA','PERIODO','OPERADOR','DISPOSITIVO','ORIGEM_REGISTRO','OBSERVACAO'],
    IMPORTACOES: ['ID_IMPORTACAO','ARQUIVO','DATA_HORA_ARQUIVO','IMPORTADO_EM','REGISTROS_LIDOS','INSCRICOES_NOVAS','PESSOAS_NOVAS','PESSOAS_ATUALIZADAS','STATUS','MENSAGEM'],
    INSCRICOES_LOCAL_CONTROLE: ['RESPONSE_ID','TIMESTAMP_RESPOSTA','STATUS','ID_PESSOA','NUMERO_INSCRICAO','PROCESSADO_EM','ERRO_TECNICO']
  }),
  CACHE_SECONDS: 21600,
  PAINEL_CACHE_SECONDS: 5,
  CAPACIDADE_EVENTO_PADRAO: 458,
  MAX_SEARCH_RESULTS: 30
});
